Program FFT
Implicit none


!INPUT DATA
INTEGER, PARAMETER :: k
!COMPLEX :: X(k)
REAL :: X(k)   !DATA VECTOR. IMAGINARTY PART SHOULD BE SET TO  ZERO.
INTEGER :: gam
INTEGER :: N=2**(gam)    !THE NUMBER OF SAMPLE POINTS
INTEGER :: NU=gam


!INITIALIZATION
INTEGER :: I
INTEGER : P
INTEGER :: l=1           !ARRAY NUMBER
INTEGER :: N2=N/2        !THE SPACINGS BETWEEN DUAL NODES
INTEGER :: NU1=gam-1   !THE RIGHT SHIFT REQRUIED WHEN DETERMINING THE VALUE OF q.
INTEGER :: k=0


COMPLEX :: T1



IF (l << gam)


I=1



